name: cstar_env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - numpy>2.0,<2.4  # currently numba doesn't support 2.4
  - xarray
  - roms-tools
  - netCDF4
  - pip
  - ipykernel
  # only needed for building docs
  - pandoc
